### ISSUE TITLE
Parties list disappear when removing google-map directive

### ISSUE THREAD

**Issue by kenp77** [Urigo/meteor-angular2.0-socially#177]
Hi,

I found a weird bug in the parties list page! 
When i remove the <sebm-google-map> directive from the parties-list.component.html page and i login the list of parties disappear and i need to force a refresh so the list can show up again ! Once i put  <sebm-google-map> back, and i login, the list is there without forcing a refresh ! How can i solve that weird bug !

**Comment by dotansimha** [comment]
@kenp77, thanks for noticing it.
We noticed another issues with the Subscription over the `Observable` returned from `meteor-rxjs` and I think this is the same issue.

Can you please add `.publishReplay(1).refCount();` to the parties cursor and test if the issue was fixed? 

It should be in `client/imports/app/shared-components/parties-list.class.ts`, line 59.

```
        this.parties = Parties.find({}, {
          sort: {
            name: nameOrder
          }
        }).zone().publishReplay(1).refCount();
```

Thanks!

**Comment by kenp77** [comment]
There's no folder called shared-components in the meteor-angular2.0-socially app. And what .publishReplay(1).refCount()  does exaclty ?
Thanks

**Comment by dotansimha** [comment]
The issues described here: https://github.com/Urigo/meteor-rxjs/issues/23
The folder I mentioned exists in the last step of the tutorial, not before, but you can add it in any step you currently in, just add it to the `.publishReplay(1).refCount()` to the end of the line that creates the `this.parties` from the Mongo Cursor. 
The `.publishReplay(1).refCount()` causes the Observable to replay the last value, and when the second "async" Pipe starts to work, it makes sure that he always get a value.

**Comment by dotansimha** [comment]
@kenp77, I updated `meteor-rxjs` version (0.4.2) in the tutorial with a fix for the issue, can you please try again to reproduce the bug now?

**Comment by kenp77** [comment]
i added `.publishReplay(1).refCount()` but still having the same issue : 

```
 this.partiesSub = MeteorObservable.subscribe('parties', options, location).zone().subscribe(() => {
        this.parties = Parties.find({}, {
          sort: {
            name: nameOrder
          }
        }).zone().publishReplay(1).refCount();
      });
```

**Comment by dotansimha** [comment]
Can you try and reproduce with the latest commit of this repository? it should work.. I can't reproduce the issue in my env...

**Comment by kenp77** [comment]
I just did a pull request but i still dont see the `.publishReplay(1).refCount()` in your parties.list.class.ts. I have the last version of the repository. The last commit you did was November 3 : Remove fastclick package. is that right ?

**Comment by kenp77** [comment]
Even i added `.publishReplay(1).refCount()` from the actual repository i still have the same issue.
Here's the scenarios : 
**Scenario 1 :**
1.  I keep the `<sebm-google-map>` directives in parties-list-component.html and parties-form.component.html
2.  I login and the parties list is displayed in the screen view.

**Scenario 2:**
1.  I removed the `<sebm-google-map>` directive in both parties-list-component.html and parties-form.component.html
2.  I login and the parties disappear from the screen view and i need to refresh the browser or click an input text box somehwere in the page to make the parties list appears again.

**Comment by dotansimha** [comment]
Yeah we fixed it internally inside `meteor-rxjs`, and I updated the package version in the tutorial, please try to remove your `node_modules` and then `npm install` again...

**Comment by dotansimha** [comment]
@kenp77 Verified it again with the scenario you wrote. All works fine. 

I am closing it at the moment, if you able to reproduce it again in the latest version (pull from master, remove `node_modules` and `npm install` again) - please re-open and provide more info.

Thanks.

**Comment by kenp77** [comment]
Still have the same issue !
I pulled from master (last update was on November 3, 12 : 45 by BAB0mB) . I removed `node_modules`and did a `meteor npm install`. I have now the `meteor-rxjs-0.4.3` version. 
Once i sign in, the parties list disapear and i need to click on an input box or force a refresh of the page to make the parties list appears. I just dont understand why when i add the `<sebm-google-map>` directive the parties list is refreshed automaticly ?

**Comment by dotansimha** [comment]
How to you login? In which step? 
The login is a separate route, and after login you are redirected to the main page, which should load the entire data from scratch...

**Comment by kenp77** [comment]
Ok, now i think you will be able to reproduce the issue if you follow these scenarios and of course you need to remove the `<sebm-google-map>` directive from the list and detail party views:
1. Do a meteor reset
2. Signup and signin with a user
3. The two public parties are not displayed and you need to click somewhere on a input box on the page so the party list can appear again

**Other scenario :** 
1. Do a meteor reset
2. Signup and sigin with a user
3. Reply to a party (after you click somewhere on a input box on the page to make the party list appear)
4. Logout and login
5. The two public parties are displayed !! 

It looks like when i reply to a party or when i put the map directive, the issue is gone  ! I just dont get it

**Comment by kenp77** [comment]
No idea how to solve this?

**Comment by kamilkisiela** [comment]
@kenp77 @dotansimha Same for me, everything works

**Comment by Urigo** [comment]
@kenp77 can you please share a repository with a reproduction?
