### ISSUE TITLE
Step 12 : Pagination exception

### ISSUE THREAD

**Issue by ashishpok** [Urigo/meteor-angular2.0-socially#95]
Most of features explained in step 12 doesnt seem to work for me - not sure if anyone else is having the same issue. 

I tried running off of [zipped source](https://github.com/Urigo/meteor-angular2.0-socially/archive/step_12.zip) post step 12 as well and getting same issue.

No bootup issues other than:
`"!!./../node_modules/css-loader/index.js!./../node_modules/less-loader/index.js!./login-buttons.less"
in
/Users/v632654/playground/socially/node_modules/angular2-meteor-accounts-ui/login-buttons.js
(web.browser)`

This seems pretty harmless - perhaps some styling issue which I dont care much at this point. 

First exception I see is switching to second page:
`Exception in queued task: EXCEPTION: Error in /client/imports/parties-list/parties-list.html:13:12
ORIGINAL EXCEPTION: TypeError: Cannot read property 'type' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'type' of undefined
    at AppElement.detachView (http://localhost:3000/packages/modules.js?hash=2a73caea10b46cc884e49ea4e9637d937ed9286c:56419:17)
    at ViewContainerRef_.remove (http://localhost:3000/packages/modules.js?hash=2a73caea10b46cc884e49ea4e9637d937ed9286c:56622:34)
    at NgFor._bulkRemove (http://localhost:3000/packages/modules.js?hash=2a73caea10b46cc884e49ea4e9637d937ed9286c:65054:37)
    at NgFor._applyChanges (http://localhost:3000/packages/modules.js?hash=2a73caea10b46cc884e49ea4e9637d937ed9286c:65019:33)
    at NgFor.ngDoCheck (http://localhost:3000/packages/modules.js?hash=2a73caea10b46cc884e49ea4e9637d937ed9286c:65005:22)
    at DebugAppView._View_PartiesList0.detectChangesInternal (PartiesList.template.js:205:42)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/packages/modules.js?hash=2a73caea10b46cc884e49ea4e9637d937ed9286c:57334:14)
    at DebugAppView.detectChanges (http://localhost:3000/packages/modules.js?hash=2a73caea10b46cc884e49ea4e9637d937ed9286c:57423:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/packages/modules.js?hash=2a73caea10b46cc884e49ea4e9637d937ed9286c:57354:34)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:3000/packages/modules.js?hash=2a73caea10b46cc884e49ea4e9637d937ed9286c:57345:14)
ERROR CONTEXT:`

Appreciate any help.

**Comment by kamilkisiela** [comment]
Because of #96 could you try it with https://github.com/Urigo/meteor-angular2.0-socially/archive/8684798.zip ?

8684798 points to step 12.19

**Comment by kamilkisiela** [comment]
@ashishpok Works fine for me :+1:

**Comment by kamilkisiela** [comment]
I updated tags so you can now use step_12 instead of commit's id.

so https://github.com/Urigo/meteor-angular2.0-socially/archive/step_12.zip should work now

**Comment by ashishpok** [comment]
Thanks @kamilkisiela, will try it.

**Comment by ashishpok** [comment]
Ok, here is what I have so far
1. Works fine in Firefox
2. Loads first page of data in Chrome (Version 49.0.2623.87 64-bit) and still shows the error when Sorting or switching page
3. Application crashes immediately in Safari - have to say I haven't tried other steps in Safari yet. I was working purely with Chrome until now.

**Comment by ashishpok** [comment]
#99 already opened for what I mentioned about Safari.

**Comment by kamilkisiela** [comment]
Couldn't reproduce that bug with pagination.

**Comment by kamilkisiela** [comment]
Should be fixed with the latest version of Socially.

@mention me if this is still an issue.

**Comment by slayerfat** [comment]
i can confirm this issue still occurs on chrome Version 51.0.2704.106 (64-bit) and firefox 47.0

i used the repo code and still fails on step 12 `TypeError: Cannot read property 'type' of undefined`, it also tries to use an array somewhere: `TypeError: Cannot read property 'splice' of null`, on firefox it throws a different error: `TypeError: view is undefined`.

the first list page works fine, as soon as i click page 2, it throws the exception

**Comment by dohomi** [comment]
I have this error in my own sample app. This is how I raise the error:

``` javascript
controller.ts 
component.constructor(){
(...)
    this.autorun(() => {
            // for debug purpose set timing
            // let start = moment();
            // depend the autorun on changes of the search and filtering
            this.searchDeps.depend();
            let terms:UserTerms = this.getTerms();
            this.subscribe('usersPublish', terms, () => {
                const parameter:UserQuery = UserQueryConstructor(terms);
                this.users = Meteor.users.find(parameter.find, parameter.options);
            }, true);

            // set countUser
            meteorUserService.countAllUsers(terms).then(r => this.countUser = r);
        }, true);
}

```

```
template.html:
    <tr *ngFor="let user of users" userItem [item]="user"
        (selectUser)="editUser = user; premiumUserId = null;"
        (selectPremium)="premiumUserId = user._id; editUser = null;">
        Loading...
    </tr>
```

Everytime I search for an item and the `ngFor`needs to complete re-render itself the following errors getting raised:

```
TypeError: Cannot read property 'type' of undefined, it also tries to use an array somewhere: TypeError: Cannot read property 'splice' of null, on firefox it throws a different error: TypeError: view is undefined.
```
